### ISSUE TITLE
Items longer than the default screen width don't wrap

### ISSUE THREAD

**Issue by gene1wood** [aegirhall/console-menu#29]
If an item is of a length greater than the screen width ([default of 80 characters](https://github.com/aegirhall/console-menu/blob/fabb641962a16a21f099dd16528db2b27e820b96/consolemenu/screen.py#L18) it doesn't wrap it merely sticks out the side of the box

# Steps to reproduce

Install `v0.5.1` with `pip install console-menu`
Create code like

```
from consolemenu import SelectionMenu

a_list = [
    "This is an option that isn't just a string under 80 characters heck it's actually quite a bit longer",
    "blue", 
    "green"]

selection = SelectionMenu.get_selection(
    a_list)
```

# Expected results

A menu like
```
  ┌─────────────────────────────────────────────────────────────────────────┐
  │                                                                         │
  │  Select an option                                                       │
  │                                                                         │
  │                                                                         │
  │    1 - This is an option that isn't just a string under 80 characters   │
           heck it's actually quite a bit longer                            │
  │    2 - blue                                                             │
  │    3 - green                                                            │
  │    4 - Exit                                                             │
  │                                                                         │
  │                                                                         │
  └─────────────────────────────────────────────────────────────────────────┘
  >> 
```

# Actual results

```
  ┌─────────────────────────────────────────────────────────────────────────┐
  │                                                                         │
  │  Select an option                                                       │
  │                                                                         │
  │                                                                         │
  │    1 - This is an option that isn't just a string under 80 characters heck it's actually quite a bit longer  │
  │    2 - blue                                                             │
  │    3 - green                                                            │
  │    4 - Exit                                                             │
  │                                                                         │
  │                                                                         │
  └─────────────────────────────────────────────────────────────────────────┘
  >> 
```

**Comment by MoralCode** [comment]
Would it be preferable to wrap, or to have the width of the default screen increase? seems to me like it may be good to have an option since ive used this library in a project as a quick-and-dirty way to display a selectable table of items by having each item be a string with tabs in it to move them into columns. This is a case where having things auto-wrap wouldn't be as great, but i also see the value in it.

on first look, it seems like these lines are where the logic would need to check for line width and split it into two lines, but maybe theres some more complexity needed to make sure the second line doesnt show up as a separate selectable menu item:

https://github.com/aegirhall/console-menu/blob/9378508bb04d2214a8f65157c2a5aa6847784a5e/consolemenu/menu_formatter.py#L274-L276

**Comment by MoralCode** [comment]
also #41 could probably be rebased and rehabilitated as a solution to this

**Comment by MoralCode** [comment]
![Screenshot_20211106_203857](https://user-images.githubusercontent.com/17362949/140628008-ce7f32ac-0270-4fd7-af03-67676aa7b82b.png)


seems like simply inserting newlines every 80 chars  isnt quite enough.
- the menu adds padding so it still runs off the side
- the edges arent added back to wrapped content
-

**Comment by MoralCode** [comment]
![Screenshot_20211106_204803](https://user-images.githubusercontent.com/17362949/140628179-f5c511c8-20f0-4670-a67a-d902a2057560.png)

simply truncating it is another possible option. visually cleaner but also far less usable

**Comment by MoralCode** [comment]
![Screenshot_20211106_210156](https://user-images.githubusercontent.com/17362949/140628443-9e78e90b-ca4e-4bd7-a2d1-3c4f7532ef2c.png)

well it works.

Still needs:
- would be nice to have it align with the text above it rather than the selection option
- still need to update the `show` function from console_menu.py per my last comment so that it splits up the content into a list. This is tricky because it will need to know how much available space there is (before padded out to the default of 80) and possibly split on a clean word boundary to avoid breaking words up.
- any unit testing, documentation, and cleanup required by the maintainers

**Comment by gene1wood** [comment]
@MoralCode Nice fix! Thanks for it!
