### ISSUE TITLE
How to use FunctionItem correctly?

### ISSUE THREAD

**Issue by Roypy** [aegirhall/console-menu#42]
I'm probably not doing it right but when I'm trying to call a function using FunctionItem It does not work like I want it to. Ive read the documentation but I just don't understand how to use it well. I just want to press the button and have it call the function but instead the function is called automatically every time I run the program.

```
from consolemenu import *
from consolemenu.items import *


def test_function():
	print("TestCall")


def welcome_screen():
	menu = ConsoleMenu("MenuTitle", "SubTitle")

	function_item = FunctionItem("Function item", test_function())

	menu.append_item(function_item)
	menu.show()


welcome_screen()
```

Output: https://gyazo.com/0c310cd95d587a66c5412f56d318aaa3

**Comment by aegirhall** [comment]
Hi @Roypy you need to remove the parentheses from test_function when creating the FunctionItem instance.   Having the parens makes it actually execute your function, rather than just passing a reference to the function.  So, it should look like this:

function_item = FunctionItem("Function item", test_function)

Note that you probably also want to add something at the end of your test_function to "pause" the screen output if you need to read any output that comes from that function.  So for example you could have your test_function look like this:

def test_function():
  print("TestCall")
  PromptUtils(Screen()).enter_to_continue()

Otherwise, any output from your functions will disappear when the screen is cleared.

**Comment by Roypy** [comment]
Thank you @aegirhall your answer solved my issue, I'm not sure how I overlooked the parenthesis but I somehow did. This is a great tool! thank you.
